import type { AdminRoleName } from "@/domain/settings/define";

export const roleLabels: Record<AdminRoleName, string> = {
  rental: "대관 담당자",
  accounting: "회계 담당자",
  system: "시스템 관리자",
};

export const auditActionLabels: Record<string, string> = {
  "setting.change": "설정 변경",
  "setting.schedule": "설정 변경 예약",
  "setting.revert": "설정 되돌리기",
  "setting.cancel_scheduled": "설정 예약 취소",
  "auth.login": "로그인",
  "auth.logout": "로그아웃",
  "auth.password_failed": "비밀번호 실패",
  "auth.totp_failed": "인증 코드 실패",
  "auth.locked": "계정 잠김",
  "auth.totp_enrolled": "2단계 인증 등록",
  "admin.created": "관리자 계정 생성",
  "setting.confirm": "설정 확정",
  "space.create": "공간 추가",
  "space.update": "공간 수정",
  "space.photo_add": "공간 사진 추가",
  "space.photo_delete": "공간 사진 삭제",
  "application.submit": "대관 신청",
  "application.payment_expired": "미결제 자동취소",
  "application.submitted": "신청접수",
  "application.reviewing": "검토 시작",
  "application.revision_requested": "보완 요청",
  "application.rejected": "반려",
  "application.confirmed": "승인(예약확정)",
  "application.withdrawn": "신청 철회",
  "application.closed_revision_expired": "보완기한 만료",
  "payment.amount_mismatch": "결제 금액 불일치",
  "payment.late": "기한 후 결제",
  "refund.succeeded": "환불 완료",
  "refund.failed": "환불 실패",
  "refund.retry": "환불 재시도",
  "pii.view": "개인정보 조회",
  "pii.download": "첨부 내려받기",
  "closure.create": "휴관 규칙 추가",
  "closure.deactivate": "휴관 규칙 끄기",
  "block.create": "일정 차단",
  "block.delete": "일정 차단 해제",
  "booking_window.set": "접수기간 설정",
  "booking_window.extend": "접수기간 연장",
  "fee_schedule.create": "요금표 저장",
  "fee_schedule.schedule": "요금표 예약",
  "fee_schedule.cancel_scheduled": "요금표 예약 취소",
  "discount.create": "감면 규칙 추가",
  "discount.update": "감면 규칙 수정",
};
